cable:
  filename%restart_in               : ""
  cable_user%CLIMATE_fromZero       : .true.
  cable_user%YearStart              : 1841
  cable_user%YearEnd                : 1870
  icycle                            : 2
  spincasa                          : .false.
  cable_user%CASA_OUT_FREQ          : "monthly"
  cable_user%CASA_fromZero          : .true.
  cable_user%CASA_DUMP_READ         : .false.
  cable_user%CASA_DUMP_WRITE        : .false.
  cable_user%CASA_SPIN_STARTYEAR    : 1850
  cable_user%CASA_SPIN_ENDYEAR      : 1859
  cable_user%limit_labile           : .true.
  casafile%cnpipool                 : ""
  cable_user%POP_fromZero           : .true.
  cable_user%POP_out                : "ini"
  cable_user%POP_restart_in         : "stage_1_climate_spinup/<run>/file.nc"
  cable_user%POPLUC                 : .true.
  cable_user%POPLUC_RunType         : "static"
  cable_user%c13o2_restart_in_flux  : ""
  cable_user%c13o2_restart_in_pools : ""
  filename%out                      : "stage_2_zero_biomass/<run>/outputs/cru_out_cable.nc"
  filename%restart_in               : "cru_out_cable"
cru:
luc:

